### ISSUE TITLE
<h2 y medio>

### ISSUE THREAD

**Issue by DanBaDo** [Tanigago/Curriculum#1]
https://github.com/Tanigago/Curriculum/blob/4fac85675446d0667d063353c32900a7ecd57797/src/noticia.html#L28

Algo pasó en esta linea. 

Lo más importante es que, independientemente de que se trate de h2 o h3, las etiquetas de encabezado no debemos de emplearlas para otras finalidades. Si deseamos destacar un texto o modificar su tamaño contaremos con otros recursos.

**Comment by Tanigago** [comment]
Revisado y modificado. Gracias.

**Comment by DanBaDo** [comment]
:+1: Close de issue!
